secondary_features = {
    "Комплектация_Гидроусилитель руля": "hydraulic_steering",
    "Комплектация_Электроусилитель руля": "el_steering",
    "Комплектация_Кондиционер": "air_conditioner",
    "Комплектация_Климат-контроль": "climate_control",
    "Комплектация_Автономный отопитель": "autonomous_heater",
    "Комплектация_Воздухо-очиститель салона": "cabin_air_filter",
    "Комплектация_Борт-компьютер": "board_computer",
    "Комплектация_Контроль давления в шинах": "tyres_pressure_cont",
    "Комплектация_Парковочн. датчик спереди": "park_sensor_front",
    "Комплектация_Парковочный датчик сзади": "park_sensor_rear",
    "Комплектация_Камера заднего вида": "rear_view_camera",
    "Комплектация_Камера ночного видения": "night_vision_camera",
    "Комплектация_Камеры кругового обзора": "panoramic cameras",
    "Комплектация_Датчик дистанции": "distance_sensor",
    "Комплектация_Датчик дождя": "rain_sensor",
    "Комплектация_Круиз-контроль": "сruise_control",
    "Комплектация_Адаптивный круиз-контроль": "adaptive_cruise_control",
    "Комплектация_Обнаружение пешеходов": "pedestrians_detection",
    "Комплектация_Автоматическая парковка": "automatic_parking",
    "Комплектация_Ассистент \"мёртвых\" зон": "blind_zones_assistant",
    "Комплектация_Ассистент движ. по полосе": "strip_moving_assistant",
    "Комплектация_Распознавание знаков": "sign_recognition",
    "Комплектация_Система экстр. торможения": "extreme_braking_system",
    "Комплектация_Keyless Go": "keyless_go",
    "Комплектация_Система Старт-Стоп": "start_stop_system",
    "Комплектация_Эл. закрытие багажника": "el_trunk_close",
    "Комплектация_Эл. задняя шторка": "el_rear_curtain",
    "Комплектация_Эл. закрываемые двери": "el_doors_close",
    "Комплектация_Реллинги на крыше": "roof_rails",
    "Комплектация_Фаркоп": "trailer_hook",
    "Комплектация_Люк": "sunroof",
    "Комплектация_Панорамный люк": "panoramic_sunroof",
    "Комплектация_Полный привод 4x4": "all_wheels_drive",
    "Комплектация_Пневмо-подвеска": "pneumatic_suspension",
    "Комплектация_Спойлер": "spoiler",
    "Комплектация_Пороги": "doorsteps",
    "Комплектация_Спорт-пакет": "sport_package",
    "Комплектация_Сервисная книжка": "service_book",
    "Комплектация_Литые диски": "alloy_wheels",
    "Салон_Кожаный салон": "leather_interior",
    "Салон_Подлокотники": "armrests",
    "Салон_Тонированные стёкла": "tinted_windows",
    "Салон_Шторки на окнах": "curtains",
    "Салон_Isofix крепления": "isofix_mounts",
    "Салон_Холодильник": "fridge",
    "Руль_Регулируемый": "steer_regulated",
    "Руль_Эл. регулируемый": "steer_el_regulated",
    "Руль_Многофункциональный": "steer_multifunc",
    "Руль_Спортивный": "steer_sport",
    "Руль_С обогревом": "steer_heated",
    "Руль_С памятью": "steer_with_memory",
    "Сидения_Эл. регулируемые": "seats_el_regualted",
    "Сидения_С обогревом": "seats_heated",
    "Сидения_Спортивные": "seats_sport",
    "Сидения_Recaro": "seats_recaro",
    "Сидения_Вентилируемые": "seats_ventilated",
    "Сидения_С массажем": "seats_with_massage",
    "Сидения_С памятью": "seats_with_memory",
    "Свет_Xenon": "xenon",
    "Свет_Bi-xenon": "bi_xenon",
    "Свет_LED": "led",
    "Свет_LED тормозной сигнал": "led_brake_signal",
    "Свет_Дополн. стоп сигнал": "additional_brake_signal",
    "Свет_Противотуманные фары": "fog_lights",
    "Свет_Омыватели фар": "headlight_washers",
    "Свет_Автомат. ближний свет": "autom_low_beam",
    "Свет_Автомат. дальний свет": "autom_high_beam",
    "Свет_Адаптивный дальний свет": "adaptive_high_beam",
    "Зеркала_Эл. регулируемые": "mirrors_el_regulated",
    "Зеркала_С обогревом": "mirrors_heated",
    "Зеркала_Затемняющиеся": "mirrors_dimming",
    "Зеркала_Спортивные": "mirrors_sport",
    "Зеркала_Эл. убирающиеся": "mirrors_el_retractable",
    "Зеркала_С памятью": "mirrors_with_memory",
    "Безопасность_ABS": "abs",
    "Безопасность_Центральный замок": "central_locking",
    "Безопасность_Сигнализация": "signaling",
    "Безопасность_Имобилайзер": "immobilizer",
    "Безопасность_Air-bag": "air_bag",
    "Безопасность_ESP": "esp",
    "Безопасность_ASR": "asr",
    "Безопасность_Маркировка": "marking",
    "Hi-Fi_FM/AM": "fm_am",
    "Hi-Fi_CD": "cd",
    "Hi-Fi_CD changer": "cd_changer",
    "Hi-Fi_DVD": "dvd",
    "Hi-Fi_DVD changer": "dvd_changer",
    "Hi-Fi_MP3": "mp3",
    "Hi-Fi_USB": "usb",
    "Hi-Fi_SDcard": "sd_card",
    "Hi-Fi_HDD": "hdd",
    "Hi-Fi_TV": "tv",
    "Hi-Fi_LCD": "lcd",
    "Hi-Fi_Навигация": "navigation",
    "Hi-Fi_Телефон": "phone",
    "Hi-Fi_Bluetooth": "bluetooth",
    "Hi-Fi_Hands-free": "hands_free",
    "Hi-Fi_Subwoofer": "subwoofer"
}


def all_features():
    return sorted(list(secondary_features.values()))
