secondary_features = {
    "Гидроусилитель руля": "hydraulic_steering",
    "Электроусилитель руля": "el_steering",
    "Кондиционер": "air_conditioner",
    "Климат-контроль": "climate_control",
    "Автономный отопитель": "autonomous_heater",
    "Воздухо-очиститель салона": "cabin_air_filter",
    "Борт-компьютер": "board_computer",
    "Контроль давления в шинах": "tyres_pressure_cont",
    "Парковочн. датчик спереди": "park_sensor_front",
    "Парковочный датчик сзади": "park_sensor_rear",
    "Камера заднего вида": "rear_view_camera",
    "Камера ночного видения": "night_vision_camera",
    "Камеры кругового обзора": "panoramic cameras",
    "Датчик дистанции": "distance_sensor",
    "Датчик дождя": "rain_sensor",
    "Круиз-контроль": "сruise_control",
    "Адаптивный круиз-контроль": "adaptive_cruise_control",
    "Обнаружение пешеходов": "pedestrians_detection",
    "Автоматическая парковка": "automatic_parking",
    "Ассистент \"мёртвых\" зон": "blind_zones_assistant",
    "Ассистент движ. по полосе": "strip_moving_assistant",
    "Распознавание знаков": "sign_recognition",
    "Система экстр. торможения": "extreme_braking_system",
    "Keyless Go": "keyless_go",
    "Система Старт-Стоп": "start_stop_system",
    "Эл. закрытие багажника": "el_trunk_close",
    "Эл. задняя шторка": "el_rear_curtain",
    "Эл. закрываемые двери": "el_doors_close",
    "Реллинги на крыше": "roof_rails",
    "Фаркоп": "trailer_hook",
    "Люк": "sunroof",
    "Панорамный люк": "panoramic_sunroof",
    "Полный привод 4x4": "all_wheels_drive",
    "Пневмо-подвеска": "pneumatic_suspension",
    "Спойлер": "spoiler",
    "Пороги": "doorsteps",
    "Спорт-пакет": "sport_package",
    "Сервисная книжка": "service_book",
    "Литые диски": "alloy_wheels",
    "Кожаный салон": "leather_interior",
    "Подлокотники": "armrests",
    "Тонированные стёкла": "tinted_windows",
    "Шторки на окнах": "curtains",
    "Isofix крепления": "isofix_mounts",
    "Холодильник": "fridge",
    "Регулируемый": "steer_regulated",
    "Эл. регулируемый": "steer_el_regulated",
    "Многофункциональный": "steer_multifunc",
    "Спортивный": "steer_sport",
    "С обогревом": "steer_heated",
    "С памятью": "steer_with_memory",
    "Эл. регулируемые": "seats_el_regualted",
    # "С обогревом": "seats_heated",  # TODO fix!
    "Спортивные": "seats_sport",
    "Recaro": "seats_recaro",
    "Вентилируемые": "seats_ventilated",
    "С массажем": "seats_with_massage",
    # "С памятью": "seats_with_memory",  # TODO fix!
    "Xenon": "xenon",
    "Bi-xenon": "bi_xenon",
    "LED": "led",
    "LED тормозной сигнал": "led_brake_signal",
    "Дополн. стоп сигнал": "additional_brake_signal",
    "Противотуманные фары": "fog_lights",
    "Омыватели фар": "headlight_washers",
    "Автомат. ближний свет": "autom_low_beam",
    "Автомат. дальний свет": "autom_high_beam",
    "Адаптивный дальний свет": "adaptive_high_beam",
    # "Эл. регулируемые": "mirrors_el_regulated",  # TODO fix
    # "С обогревом": "mirrors_heated",  # TODO fix
    "Затемняющиеся": "mirrors_dimming",
    # "Спортивные": "mirrors_sport",  # TODO fix
    "Эл. убирающиеся": "mirrors_el_retractable",
    # "С памятью": "mirrors_with_memory",  # TODO fix
    "ABS": "abs",
    "Центральный замок": "central_locking",
    "Сигнализация": "signaling",
    "Имобилайзер": "immobilizer",
    "Air-bag": "air_bag",
    "ESP": "esp",
    "ASR": "asr",
    "Маркировка": "marking",
    "FM/AM": "fm_am",
    "CD": "cd",
    "CD changer": "cd_changer",
    "DVD": "dvd",
    "DVD changer": "dvd_changer",
    "MP3": "mp3",
    "USB": "usb",
    "SDcard": "sd_card",
    "HDD": "hdd",
    "TV": "tv",
    "LCD": "lcd",
    "Навигация": "navigation",
    "Телефон": "phone",
    "Bluetooth": "bluetooth",
    "Hands-free": "hands_free",
    "Subwoofer": "subwoofer"
}


def all_features():
    return sorted(list(secondary_features.values()))
